### ISSUE TITLE
`env` and `ecmaFeatures` should be objects, not arrays

### ISSUE THREAD

**Issue by IanVS** [pirosikick/eslintrc-editor#5]
Currently, the editor will create a config file that sets `env` and `ecmaFeatures` to arrays, like so:

``` json
{
  "env": [
    "node"
  ],
  "globals": {},
  "ecmaFeatures": [
    "blockBindings"
  ],
  "rules": {}
}
```

However, attempting to run with this config will result in an error being thrown:

```
Error: Environment must not be an array
```

Also, `blockBindings` will not be set (but there is no error there).  Both of these properties should be objects, as shown in the ESLint [docs](http://eslint.org/docs/user-guide/configuring).

**Comment by pirosikick** [comment]
@IanVS Thank you for reporting this issue. I'll fix this soon.

**Comment by pirosikick** [comment]
@IanVS I fixed the problem. Please check the current version.
https://pirosikick.github.io/eslintrc-editor/

**Comment by IanVS** [comment]
Checked on mobile chrome, looks good now.  Thanks!
