### ISSUE TITLE
Unable to locate settings for React

### ISSUE THREAD

**Issue by JaxCavalera** [pirosikick/eslintrc-editor#8]
Would it be possible to include settings for please : 
https://github.com/yannickcr/eslint-plugin-react

I tried to locate these inside the web application but was unable to find them if they are already included.

There may be a problem with the **no deprecation** React rule but other than that the rest seems to all work fine if manually added, would just be nice to have all configuration options located in the one place.

**Comment by pirosikick** [comment]
OK, I'll add the settings to the web application and make such additional rules more pluggable.

**Comment by JaxCavalera** [comment]
Thank you very much ^ ^
